name: mtw
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - attr=2.5.1
  - attrs=22.1.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - bleach=4.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - dbus=1.13.18
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.76.1
  - glib-tools=2.76.1
  - graphite2=1.3.14
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - harfbuzz=6.0.0
  - icu=72.1
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - ipykernel=5.5.5
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jinja2=3.1.2
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=5.2.0
  - jupyter_core=4.5.0
  - jupyterlab_widgets=1.0.0
  - keyutils=1.6.1
  - krb5=1.20.1
  - lame=3.100
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=16.0.1
  - libclang13=16.0.1
  - libcups=2.3.3
  - libedit=3.1.20221030
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.76.1
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm16=16.0.1
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.2
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=253
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.4
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mistune=0.8.4
  - mpg123=1.31.3
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbconvert=5.5.0
  - nbformat=5.7.0
  - ncurses=6.4
  - notebook=5.7.11
  - nspr=4.35
  - nss=3.89
  - numpy=1.21.6
  - openssl=3.1.0
  - packaging=22.0
  - pandoc=2.12
  - pandocfilters=1.5.0
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - ply=3.11
  - portaudio=19.6.0
  - prometheus_client=0.14.1
  - prompt_toolkit=1.0.15
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pulseaudio-client=16.1
  - pycparser=2.21
  - pygments=2.11.2
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - python=3.7.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-sounddevice=0.4.1
  - python_abi=3.7
  - pyzmq=23.2.0
  - qt-main=5.15.8
  - qtconsole=5.4.0
  - qtpy=2.2.0
  - readline=8.2
  - scipy=1.7.3
  - send2trash=1.8.0
  - simplegeneric=0.8.1
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - terminado=0.17.1
  - testpath=0.6.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.7.1
  - tree=2.1.0
  - typing_extensions=4.1.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.38.4
  - widgetsnbextension=3.5.2
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - cycler==0.11.0
    - fonttools==4.38.0
    - jupyter-core==4.12.0
    - kiwisolver==1.4.4
    - matplotlib==3.5.3
    - pillow==9.5.0
    - pyparsing==3.0.9
    - pywdf==0.0.1
    - setuptools==58.0.4
